Do not import certain modules since they create incompatibility issues with PyTorch's version in Edgar
AttributeError: module 'torch.jit' has no attribute '_script_if_tracing'